/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-explicit-any */
import Head from "next/head";
import { useState } from "react";
import ItemSelection from "./ItemSelection";
import InitialSurvey from "./InitialSurvey";
import BodyMeasure from "./BodyMeasure";
import ClothingResults from "./ClothingResults"; 

export default function Home() {
  const [gender, setGender] = useState("mens");
  const [showInitalSurvey, setShowInitialSurvey] = useState(true);
  const [showItemSelection, setShowItemSelection] = useState(false);
  const [showBodyMeasure, setShowBodyMeasure] = useState(false);
  const [showFinalResults, setShowFinalResults] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          showInitalSurvey &&
            <InitialSurvey surveyFinished={(data:any) => {
              setGender(data.gender);
              setShowInitialSurvey(false);
              setShowBodyMeasure(true);
            }}/>
        }
        {
          showBodyMeasure &&
            <BodyMeasure measureFinished={() => {
              setShowBodyMeasure(false);
              setShowItemSelection(true);
            }}/>
        }
        {
          showItemSelection &&
            <ItemSelection selectionFinished={() => {
              setShowItemSelection(false);
              setShowFinalResults(true);
 
            }}
            gender={gender}/>
        } 
        {
          showFinalResults &&
            <ClothingResults/>
        }
      </main>
    </>
  );
}
